trigger:
  - main

pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_STATIC_WEB_APPS_API_TOKEN: $(AZURE_STATIC_WEB_APPS_API_TOKEN_SECRET)
  MONGODB_URI: $(MONGODB_URI_SECRET)

stages:
- stage: Build
  jobs:
  - job: BuildAndDeploy
    steps:
    - checkout: self
      submodules: true
    
    - task: AzureStaticWebApp@0
      inputs:
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
        app_location: '/'
        api_location: 'api'
        output_location: 'dist'
      env:
        MONGODB_URI: $(MONGODB_URI)
